# примеры API-запросов

@baseUrl = http://localhost:5000

# Загрузить фото
POST {{baseUrl}}/upscale
Content-Type: application/json

{
  "image": "lama_300px.png"
}

###

# получение статуса
GET {{baseUrl}}/tasks/9cc46064-2392-47ad-b1f8-9ebba745c7fa
Content-Type: application/json