# примеры API-запросов

@baseUrl = http://localhost:5000

# Загрузить фото
POST {{baseUrl}}/upscale
Content-Type: application/json

{
  "image": "lama_300px.png"
}

###

# получение статуса
GET {{baseUrl}}/tasks/6dc27541-4eec-42ae-8193-4ea115b3ebd0
Content-Type: application/json